first_user = User.create(name: "Tom", photo: "https://images-na.ssl-images-amazon.com/images/S/cmx-images-prod/Item/48457/DIG010147_1._SX360_QL80_TTD_.jpg", bio: "Teacher from Mexico.")
second_user = User.create(name: "Lilly", photo: "https://images-na.ssl-images-amazon.com/images/S/cmx-images-prod/Item/48457/DIG010147_1._SX360_QL80_TTD_.jpg", bio: "Teacher from Poland.")

first_post = Post.create(user_id: first_user.id, title: "My first Post", text: LoremIpsum.short)
second_post = Post.create(user_id: first_user.id, title: "My second Post", text: LoremIpsum.long)
third_post = Post.create(user_id: first_user.id, title: "My third Post", text: LoremIpsum.lorem_ipsum(paragraphs: 10))
forth_post = Post.create(user_id: first_user.id, title: "My fourth Post", text: LoremIpsum.lorem_ipsum)

fifth_post = Post.create(user_id: second_user.id, title: "My first Post", text: LoremIpsum.lorem_ipsum)
sixth_post = Post.create(user_id: second_user.id, title: "My second Post", text: LoremIpsum.lorem_ipsum(paragraphs: 10))

Comment.create(post_id: first_post.id, user_id: second_user.id, text: "Great post!")
Comment.create(post_id: first_post.id, user_id: first_user.id, text: "Thanks!")
Comment.create(post_id: first_post.id, user_id: first_user.id, text: "What did you like about it?")
Comment.create(post_id: first_post.id, user_id: second_user.id, text: "Cool things!")
Comment.create(post_id: first_post.id, user_id: first_user.id, text: "Right?")
Comment.create(post_id: first_post.id, user_id: second_user.id, text: "Yes!")
Comment.create(post_id: fifth_post.id, user_id: first_user.id, text: "Nice post!")
Comment.create(post_id: fifth_post.id, user_id: second_user.id, text: "Thanks!")

Like.create(post_id: first_post.id, user_id: second_user.id)
Like.create(post_id: first_post.id, user_id: second_user.id)
Like.create(post_id: first_post.id, user_id: second_user.id)
Like.create(post_id: fifth_post.id, user_id: first_user.id)
Like.create(post_id: fifth_post.id, user_id: second_user.id)
